# Travis-CI configuration file for Plinth

language: python
python:
  - "3.2"

# Debian packages required
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install network-manager python3-dbus python3-gi

virtualenv:
  system_site_packages: true

# Command to install dependencies
install: "pip install -r requirements.txt"

# Command to run tests
script: python3 setup.py test

notifications:
  email:
    on_success: change
    on_failure: always
  irc:
    channels:
      - "irc.oftc.net#freedombox"
    on_success: always
    on_failure: always
